/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import MODELO.Usuario;
import Conexion.Conexion;
import Controlador.UsuarioDAO;

import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author anemn
 */
public class Login extends javax.swing.JFrame {
UsuarioDAO uDAO = new UsuarioDAO();
    boolean mostrarUsuario = false;
    public static boolean bandera;
   
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lbl_iniciarSesion = new javax.swing.JLabel();
        lbl_usuario = new javax.swing.JLabel();
        txt_usuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_contraseña = new javax.swing.JPasswordField();
        btn_Ingresar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));
        jPanel1.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 350));

        lbl_iniciarSesion.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        lbl_iniciarSesion.setText("Iniciar Sesión");
        bg.add(lbl_iniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 160, 50));

        lbl_usuario.setText("Usuario");
        bg.add(lbl_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, -1, -1));
        bg.add(txt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 130, 20));

        jLabel1.setText("Contraseña");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));
        bg.add(txt_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 130, 20));

        btn_Ingresar.setText("Ingresar");
        btn_Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_IngresarActionPerformed(evt);
            }
        });
        bg.add(btn_Ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 90, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DALL·E_2024-11-21_16.33.50_-_A_minimalist_icon_design_featuring_the_silhouette_of_a_horse__styled_similarly_to_typical_user_profile_icons._The_horse_silhouette_is_sleek_and_modern_(2)-transformed.jpeg"))); // NOI18N
        bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 160, 160));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_IngresarActionPerformed
     Connection c = Conexion.getConexion();
      if (verificar()) {
        FuncionImprimirUsuario(txt_usuario.getText());
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                if (mostrarUsuario) {
                    
                    VentanaInicio ventanaInicio = new VentanaInicio();
                    ventanaInicio.setVisible(true);
                } else {
                    VentanaInicio ventanaInicio = new VentanaInicio();
                    ventanaInicio.setVisible(true);
                }
            }
        });
        setVisible(false);
    } else {
        JOptionPane.showMessageDialog(null, "El nombre de usuario o la contraseña son incorrectos");
    }
    }//GEN-LAST:event_btn_IngresarActionPerformed
public boolean verificar(){
    try{ ArrayList<Usuario> listaUsuario uDAO.buscarUsuario ("SELECT * FROM usuarios WHERE usuario = '"+txt_usuario.getText()+"'");
      
    if (listaUsuario.size()!=0 && bandera) {
                Usuario usuario = listaUsuarios.get(0);
                return usuario.getContraseña().equals(txt_contrasena.getText());
        } else {
               return false;
        }

        } catch (InterruptedException | NullPointerException e) {
            e.printStackTrace();
        }
    return true;
    
}
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btn_Ingresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_iniciarSesion;
    private javax.swing.JLabel lbl_usuario;
    private javax.swing.JPasswordField txt_contraseña;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
