/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author anemn
 */
public class VentanaInicio extends javax.swing.JFrame {

    /**
     * Creates new form VentanaInicio
     */
    public VentanaInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG = new javax.swing.JPanel();
        ABCC = new javax.swing.JInternalFrame();
        Fondo = new javax.swing.JPanel();
        lbl_titulo = new javax.swing.JLabel();
        Boton_Memento = new javax.swing.JButton();
        btn_altas = new javax.swing.JButton();
        btn_bajas = new javax.swing.JButton();
        btn_cambios = new javax.swing.JButton();
        lbl_img = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lbl_numControl = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_numcontrol = new javax.swing.JTextPane();
        lbl_nombre = new javax.swing.JLabel();
        lbl_primerap = new javax.swing.JLabel();
        lbl_segundoap = new javax.swing.JLabel();
        lbl_carrera = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_nombre = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        txt_primerap = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jComboBox1 = new javax.swing.JComboBox<>();
        lbl_semestre = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        lbl_Edad = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txt_edad = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        JM_Alumnos = new javax.swing.JMenu();
        JM_Altas = new javax.swing.JMenuItem();
        JM_Bajas = new javax.swing.JMenuItem();
        JM_Cambios = new javax.swing.JMenuItem();
        JM_Consultas = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        Grafico = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BG.setBackground(new java.awt.Color(255, 255, 255));
        BG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ABCC.setVisible(true);

        Fondo.setBackground(new java.awt.Color(153, 0, 0));

        lbl_titulo.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        lbl_titulo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_titulo.setText("ALTAS");

        Boton_Memento.setBackground(new java.awt.Color(255, 153, 0));
        Boton_Memento.setText("CANCELAR");

        btn_altas.setBackground(new java.awt.Color(153, 255, 153));
        btn_altas.setText("Dar de Alta");

        btn_bajas.setBackground(new java.awt.Color(255, 51, 51));
        btn_bajas.setText("Dar de Baja");
        btn_bajas.setPreferredSize(new java.awt.Dimension(115, 40));

        btn_cambios.setBackground(new java.awt.Color(204, 204, 0));
        btn_cambios.setText("Cambiar");
        btn_cambios.setPreferredSize(new java.awt.Dimension(115, 40));
        btn_cambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cambiosActionPerformed(evt);
            }
        });

        lbl_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icono_Altas1.png"))); // NOI18N
        lbl_img.setText("jLabel2");

        javax.swing.GroupLayout FondoLayout = new javax.swing.GroupLayout(Fondo);
        Fondo.setLayout(FondoLayout);
        FondoLayout.setHorizontalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_img, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Boton_Memento, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_cambios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_bajas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_altas, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        FondoLayout.setVerticalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_img)
                            .addComponent(lbl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_cambios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_bajas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_altas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Boton_Memento, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Numero de Control", "Nombre", "Primer Apellido", "Segundo Apellido", "Carrera", "Semestre", "Edad", "Promedio"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        lbl_numControl.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lbl_numControl.setText("Numero de Control");

        jScrollPane2.setViewportView(txt_numcontrol);

        lbl_nombre.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lbl_nombre.setText("Nombre");

        lbl_primerap.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lbl_primerap.setText("Primer Apellido");

        lbl_segundoap.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lbl_segundoap.setText("Segundo Apellido");

        lbl_carrera.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lbl_carrera.setText("Carrera");

        jScrollPane3.setViewportView(txt_nombre);

        jScrollPane4.setViewportView(txt_primerap);

        jScrollPane5.setViewportView(jTextPane1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ISC", "IM", "IAA", "LA", "LCP" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        lbl_semestre.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lbl_semestre.setText("Semestre");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1°", "2°", "3°", "4°", "5°", "6°", "7°", "8°", "9°" }));

        lbl_Edad.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lbl_Edad.setText("Edad");

        jScrollPane6.setViewportView(txt_edad);

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setText("Promedio");

        jScrollPane7.setViewportView(jTextPane2);

        javax.swing.GroupLayout ABCCLayout = new javax.swing.GroupLayout(ABCC.getContentPane());
        ABCC.getContentPane().setLayout(ABCCLayout);
        ABCCLayout.setHorizontalGroup(
            ABCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(ABCCLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(ABCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_nombre)
                    .addComponent(lbl_segundoap)
                    .addComponent(lbl_primerap)
                    .addComponent(lbl_numControl))
                .addGap(37, 37, 37)
                .addGroup(ABCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(114, 114, 114)
                .addGroup(ABCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ABCCLayout.createSequentialGroup()
                        .addGroup(ABCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ABCCLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ABCCLayout.createSequentialGroup()
                                .addComponent(lbl_Edad)
                                .addGap(30, 30, 30)))
                        .addGroup(ABCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                            .addComponent(jScrollPane6)))
                    .addGroup(ABCCLayout.createSequentialGroup()
                        .addGroup(ABCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_carrera)
                            .addComponent(lbl_semestre))
                        .addGap(30, 30, 30)
                        .addGroup(ABCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ABCCLayout.setVerticalGroup(
            ABCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ABCCLayout.createSequentialGroup()
                .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ABCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_numControl)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ABCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_carrera)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(ABCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_nombre)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ABCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_semestre)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(ABCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4)
                    .addComponent(lbl_Edad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane6)
                    .addComponent(lbl_primerap))
                .addGroup(ABCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ABCCLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(ABCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_segundoap)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ABCCLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ABCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        BG.add(ABCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 550));

        JM_Alumnos.setText("Alumnos");

        JM_Altas.setText("Altas");
        JM_Altas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_AltasActionPerformed(evt);
            }
        });
        JM_Alumnos.add(JM_Altas);

        JM_Bajas.setText("Bajas");
        JM_Bajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_BajasActionPerformed(evt);
            }
        });
        JM_Alumnos.add(JM_Bajas);

        JM_Cambios.setText("Cambios");
        JM_Cambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_CambiosActionPerformed(evt);
            }
        });
        JM_Alumnos.add(JM_Cambios);

        JM_Consultas.setText("Consultas");
        JM_Alumnos.add(JM_Consultas);

        jMenuBar1.add(JM_Alumnos);

        jMenu2.setText("Tutores");
        jMenuBar1.add(jMenu2);

        jMenu1.setText("Otros");

        Grafico.setText("Graficos");
        jMenu1.add(Grafico);

        jMenuItem2.setText("Reportes");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Vista con JOINS");
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Function");
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btn_cambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cambiosActionPerformed
        
          
    }//GEN-LAST:event_btn_cambiosActionPerformed

    private void JM_AltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_AltasActionPerformed
        Grafico.setEnabled(true);
        //FrameConsultas.setVisible(false);
        ABCC.setVisible(true);
        //Fondo.setBounds(0, 0, 710, 80);
        Fondo.setBackground(new java.awt.Color(179, 239, 26));
        lbl_titulo.setBounds(100, 10, 160, 70);
        lbl_titulo.setText("ALTAS");
        lbl_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MIEMBRO_ADD.png")));
        btn_bajas.setVisible(false);
        btn_altas.setVisible(true);
        btn_cambios.setVisible(false);
        //actualizarTablas(jTable1);
        //Estado_Cuenta.setVisible(false);
        //Caja_Estado_Cuenta.setVisible(false);
        //metodoMagicoParaRestablecerComponentes(Caja_Nombre_Paciente, Caja_ApellidoP, Caja_Domicilio, Caja_telefono, Tipo_Seguro, ComboSala, Caja_ID, Caja_Estado_Cuenta);
        Boton_Memento.setEnabled(false);
        
        
        
    }//GEN-LAST:event_JM_AltasActionPerformed

    private void JM_BajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_BajasActionPerformed
 Grafico.setEnabled(true);
        //FrameConsultas.setVisible(false);
        ABCC.setVisible(true);
        //Fondo.setBounds(0, 0, 710, 80);
        Fondo.setBackground(new java.awt.Color(204, 72, 12));
        lbl_titulo.setBounds(100, 10, 160, 70);
        lbl_titulo.setText("BAJAS");
        lbl_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Borrar_Miembro.png"))); 
        btn_bajas.setVisible(true);
        btn_altas.setVisible(false);
        btn_cambios.setVisible(false);
        //actualizarTablas(jTable1);
        //Estado_Cuenta.setVisible(true);
        //Caja_Estado_Cuenta.setVisible(true);
        //metodoMagicoParaRestablecerComponentes(Caja_Nombre_Paciente, Caja_ApellidoP, Caja_Domicilio, Caja_telefono, Tipo_Seguro, ComboSala, Caja_ID, Caja_Estado_Cuenta);
          Boton_Memento.setEnabled(false);    }//GEN-LAST:event_JM_BajasActionPerformed

    private void JM_CambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_CambiosActionPerformed
        Grafico.setEnabled(true);
        //FrameConsultas.setVisible(false);
        ABCC.setVisible(true);
        Fondo.setBounds(0, 0, 710, 80);
        Fondo.setBackground(new java.awt.Color(161, 215, 225));
        lbl_titulo.setBounds(100, 10, 230, 70);
        lbl_titulo.setText("CAMBIOS");
        lbl_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Cambiar_Miembro.png")));
        btn_bajas.setVisible(false);
        btn_altas.setVisible(false);
        btn_cambios.setVisible(true);
        //actualizarTablas(jTable1);
        //Estado_Cuenta.setVisible(true);
        //Caja_Estado_Cuenta.setVisible(true);
        //metodoMagicoParaRestablecerComponentes(Caja_Nombre_Paciente, Caja_ApellidoP, Caja_Domicilio, Caja_telefono, Tipo_Seguro, ComboSala, Caja_ID, Caja_Estado_Cuenta);
          Boton_Memento.setEnabled(false);
        
        
    }//GEN-LAST:event_JM_CambiosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame ABCC;
    private javax.swing.JPanel BG;
    private javax.swing.JButton Boton_Memento;
    private javax.swing.JPanel Fondo;
    private javax.swing.JMenuItem Grafico;
    private javax.swing.JMenuItem JM_Altas;
    private javax.swing.JMenu JM_Alumnos;
    private javax.swing.JMenuItem JM_Bajas;
    private javax.swing.JMenuItem JM_Cambios;
    private javax.swing.JMenuItem JM_Consultas;
    private javax.swing.JButton btn_altas;
    private javax.swing.JButton btn_bajas;
    private javax.swing.JButton btn_cambios;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JLabel lbl_Edad;
    private javax.swing.JLabel lbl_carrera;
    private javax.swing.JLabel lbl_img;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_numControl;
    private javax.swing.JLabel lbl_primerap;
    private javax.swing.JLabel lbl_segundoap;
    private javax.swing.JLabel lbl_semestre;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JTextPane txt_edad;
    private javax.swing.JTextPane txt_nombre;
    private javax.swing.JTextPane txt_numcontrol;
    private javax.swing.JTextPane txt_primerap;
    // End of variables declaration//GEN-END:variables
}
