/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import Controlador.AlumnoDAO;
import MODELO.Memento;
import MODELO.alumno;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SpinnerModel;

/**
 *
 * @author anemn
 */
public class VentanaInicio extends javax.swing.JFrame {

    AlumnoDAO a1DAO = new AlumnoDAO();
    alumno a1;
    int cont;
    Fachada f1 = new Fachada();
    private Memento ultimomemento;
    
    
    public VentanaInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG = new javax.swing.JPanel();
        ABCC = new javax.swing.JInternalFrame();
        Fondo = new javax.swing.JPanel();
        lbl_titulo = new javax.swing.JLabel();
        Boton_Memento = new javax.swing.JButton();
        btn_altas = new javax.swing.JButton();
        btn_bajas = new javax.swing.JButton();
        btn_cambios = new javax.swing.JButton();
        lbl_img = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lbl_numControl = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_numcontrol = new javax.swing.JTextPane();
        lbl_nombre = new javax.swing.JLabel();
        lbl_primerap = new javax.swing.JLabel();
        lbl_segundoap = new javax.swing.JLabel();
        lbl_carrera = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_nombre = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        txt_primerap = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        txt_segundoAp = new javax.swing.JTextPane();
        JCB_Carrera = new javax.swing.JComboBox<>();
        lbl_semestre = new javax.swing.JLabel();
        JCB_Semestre = new javax.swing.JComboBox<>();
        lbl_Edad = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txt_edad = new javax.swing.JTextPane();
        lbl_promedio = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txt_promedio = new javax.swing.JTextPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        JM_Alumnos = new javax.swing.JMenu();
        JM_Altas = new javax.swing.JMenuItem();
        JM_Bajas = new javax.swing.JMenuItem();
        JM_Cambios = new javax.swing.JMenuItem();
        JM_Consultas = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        Grafico = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        JM_Funcion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BG.setBackground(new java.awt.Color(255, 255, 255));
        BG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ABCC.setVisible(true);

        Fondo.setBackground(new java.awt.Color(153, 0, 0));

        lbl_titulo.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        lbl_titulo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_titulo.setText("ALTAS");

        Boton_Memento.setBackground(new java.awt.Color(255, 153, 0));
        Boton_Memento.setText("CANCELAR");

        btn_altas.setBackground(new java.awt.Color(153, 255, 153));
        btn_altas.setText("Dar de Alta");
        btn_altas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_altasActionPerformed(evt);
            }
        });

        btn_bajas.setBackground(new java.awt.Color(255, 51, 51));
        btn_bajas.setText("Dar de Baja");
        btn_bajas.setPreferredSize(new java.awt.Dimension(115, 40));
        btn_bajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bajasActionPerformed(evt);
            }
        });

        btn_cambios.setBackground(new java.awt.Color(204, 204, 0));
        btn_cambios.setText("Cambiar");
        btn_cambios.setPreferredSize(new java.awt.Dimension(115, 40));
        btn_cambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cambiosActionPerformed(evt);
            }
        });

        lbl_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icono_Altas1.png"))); // NOI18N
        lbl_img.setText("jLabel2");

        javax.swing.GroupLayout FondoLayout = new javax.swing.GroupLayout(Fondo);
        Fondo.setLayout(FondoLayout);
        FondoLayout.setHorizontalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_img, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Boton_Memento, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_cambios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_bajas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_altas, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        FondoLayout.setVerticalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_img)
                            .addComponent(lbl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_cambios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_bajas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_altas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Boton_Memento, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseReleased(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Numero de Control", "Nombre", "Primer Apellido", "Segundo Apellido", "Carrera", "Semestre", "Edad", "Promedio"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        lbl_numControl.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lbl_numControl.setText("Numero de Control");

        txt_numcontrol.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_numcontrolKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_numcontrolKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(txt_numcontrol);

        lbl_nombre.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lbl_nombre.setText("Nombre");

        lbl_primerap.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lbl_primerap.setText("Primer Apellido");

        lbl_segundoap.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lbl_segundoap.setText("Segundo Apellido");

        lbl_carrera.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lbl_carrera.setText("Carrera");

        txt_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_nombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nombreKeyTyped(evt);
            }
        });
        jScrollPane3.setViewportView(txt_nombre);

        txt_primerap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_primerapKeyTyped(evt);
            }
        });
        jScrollPane4.setViewportView(txt_primerap);

        txt_segundoAp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_segundoApKeyTyped(evt);
            }
        });
        jScrollPane5.setViewportView(txt_segundoAp);

        JCB_Carrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleciona", "ISC", "IM", "IAA", "LA", "LCP" }));
        JCB_Carrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCB_CarreraActionPerformed(evt);
            }
        });

        lbl_semestre.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lbl_semestre.setText("Semestre");

        JCB_Semestre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleciona", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        lbl_Edad.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lbl_Edad.setText("Edad");

        txt_edad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_edadKeyTyped(evt);
            }
        });
        jScrollPane6.setViewportView(txt_edad);

        lbl_promedio.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lbl_promedio.setText("Promedio");

        txt_promedio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_promedioKeyTyped(evt);
            }
        });
        jScrollPane7.setViewportView(txt_promedio);

        javax.swing.GroupLayout ABCCLayout = new javax.swing.GroupLayout(ABCC.getContentPane());
        ABCC.getContentPane().setLayout(ABCCLayout);
        ABCCLayout.setHorizontalGroup(
            ABCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(ABCCLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(ABCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_nombre)
                    .addComponent(lbl_segundoap)
                    .addComponent(lbl_primerap)
                    .addComponent(lbl_numControl))
                .addGap(37, 37, 37)
                .addGroup(ABCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(114, 114, 114)
                .addGroup(ABCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ABCCLayout.createSequentialGroup()
                        .addGroup(ABCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ABCCLayout.createSequentialGroup()
                                .addComponent(lbl_promedio, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ABCCLayout.createSequentialGroup()
                                .addComponent(lbl_Edad)
                                .addGap(30, 30, 30)))
                        .addGroup(ABCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                            .addComponent(jScrollPane6)))
                    .addGroup(ABCCLayout.createSequentialGroup()
                        .addGroup(ABCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_carrera)
                            .addComponent(lbl_semestre))
                        .addGap(30, 30, 30)
                        .addGroup(ABCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JCB_Semestre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JCB_Carrera, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ABCCLayout.setVerticalGroup(
            ABCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ABCCLayout.createSequentialGroup()
                .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ABCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_numControl)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ABCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_carrera)
                        .addComponent(JCB_Carrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(ABCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_nombre)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ABCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_semestre)
                        .addComponent(JCB_Semestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(ABCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4)
                    .addComponent(lbl_Edad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane6)
                    .addComponent(lbl_primerap))
                .addGroup(ABCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ABCCLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(ABCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_segundoap)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ABCCLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ABCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_promedio))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        BG.add(ABCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 750, 550));

        JM_Alumnos.setText("Alumnos");

        JM_Altas.setText("Altas");
        JM_Altas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_AltasActionPerformed(evt);
            }
        });
        JM_Alumnos.add(JM_Altas);

        JM_Bajas.setText("Bajas");
        JM_Bajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_BajasActionPerformed(evt);
            }
        });
        JM_Alumnos.add(JM_Bajas);

        JM_Cambios.setText("Cambios");
        JM_Cambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_CambiosActionPerformed(evt);
            }
        });
        JM_Alumnos.add(JM_Cambios);

        JM_Consultas.setText("Consultas");
        JM_Alumnos.add(JM_Consultas);

        jMenuBar1.add(JM_Alumnos);

        jMenu2.setText("Tutores");
        jMenuBar1.add(jMenu2);

        jMenu1.setText("Otros");

        Grafico.setText("Graficos");
        jMenu1.add(Grafico);

        jMenuItem2.setText("Reportes");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Vista con JOINS");
        jMenu1.add(jMenuItem3);

        JM_Funcion.setText("Function");
        JM_Funcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_FuncionActionPerformed(evt);
            }
        });
        jMenu1.add(JM_Funcion);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JCB_CarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCB_CarreraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCB_CarreraActionPerformed

    private void btn_cambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cambiosActionPerformed
try {
        // Validar si los campos están completos
        if (txt_numcontrol.getText().isEmpty() || 
            txt_nombre.getText().isEmpty() || 
            txt_primerap.getText().isEmpty() || 
            txt_segundoAp.getText().isEmpty() || 
            txt_edad.getText().isEmpty() || 
            txt_promedio.getText().isEmpty() || 
            JCB_Carrera.getSelectedIndex() == 0 || 
            JCB_Semestre.getSelectedIndex() == 0) {
            
            JOptionPane.showMessageDialog(null, "VERIFICA QUE TODOS LOS CAMPOS ESTÉN COMPLETOS");
            return;
        }

        // Validar si el promedio está en el rango permitido
        double promedio = Double.parseDouble(txt_promedio.getText().trim());
        if (promedio < 0 || promedio > 100) {
            JOptionPane.showMessageDialog(null, "El promedio debe estar entre 0 y 100.");
            return;
        }

        // Crear un nuevo objeto alumno con los datos ingresados
        alumno a1 = new alumno(
            Integer.parseInt(txt_numcontrol.getText().trim()),  // Número de control
            promedio,                                          // Promedio
            txt_nombre.getText().trim(),                      // Nombre
            txt_primerap.getText().trim(),                    // Primer apellido
            txt_segundoAp.getText().trim(),                   // Segundo apellido
            JCB_Carrera.getSelectedItem().toString(),         // Carrera
            Integer.parseInt(JCB_Semestre.getSelectedItem().toString()), // Semestre
            Integer.parseInt(txt_edad.getText().trim())        // Edad
        );

        // Actualizar el alumno en la base de datos
        if (f1.FachadaActualizarAlumnos(a1)) {
            // Mostrar mensaje de éxito
            JOptionPane.showMessageDialog(null, "El Alumno se ha actualizado correctamente");

            // Actualizar la tabla con los nuevos datos
            actualizarTablas(jTable1);

            // Restablecer los campos de entrada
            metodoMagicoParaRestablecerComponentes(
                txt_numcontrol, 
                txt_promedio, 
                txt_nombre, 
                txt_primerap, 
                txt_segundoAp, 
                JCB_Carrera, 
                JCB_Semestre, 
                txt_edad
            );

            // Habilitar el botón de Memento
            Boton_Memento.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(null, "No se pudo actualizar el alumno. Verifique los datos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Error: Verifique que los datos sean correctos y numéricos.", "Error", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Ocurrió un error inesperado: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_btn_cambiosActionPerformed

    private void JM_AltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_AltasActionPerformed
        Grafico.setEnabled(true);
        //FrameConsultas.setVisible(false);
        ABCC.setVisible(true);
        //Fondo.setBounds(0, 0, 710, 80);
        Fondo.setBackground(new java.awt.Color(179, 239, 26));
        lbl_titulo.setBounds(100, 10, 160, 70);
        lbl_titulo.setText("ALTAS");
        //lbl_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MIEMBRO_ADD.png")));
        btn_bajas.setVisible(false);
        btn_altas.setVisible(true);
        btn_cambios.setVisible(false);
        actualizarTablas(jTable1);
        //Estado_Cuenta.setVisible(false);
        //Caja_Estado_Cuenta.setVisible(false);
        metodoMagicoParaRestablecerComponentes(txt_numcontrol,
                txt_promedio,
                txt_nombre,
                txt_primerap,
                txt_segundoAp,
                JCB_Carrera,
                JCB_Semestre,
                txt_edad);
        Boton_Memento.setEnabled(true);
        Boton_Memento.setEnabled(false);
        
        
        
    }//GEN-LAST:event_JM_AltasActionPerformed

    private void JM_BajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_BajasActionPerformed
 Grafico.setEnabled(true);
        //FrameConsultas.setVisible(false);
        ABCC.setVisible(true);
        //Fondo.setBounds(0, 0, 710, 80);
        Fondo.setBackground(new java.awt.Color(204, 72, 12));
        lbl_titulo.setBounds(100, 10, 160, 70);
        lbl_titulo.setText("BAJAS");
        //lbl_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Borrar_Miembro.png"))); 
        btn_bajas.setVisible(true);
        btn_altas.setVisible(false);
        btn_cambios.setVisible(false);
        //actualizarTablas(jTable1);
        //Estado_Cuenta.setVisible(true);
        //Caja_Estado_Cuenta.setVisible(true);
       metodoMagicoParaRestablecerComponentes(txt_numcontrol,
                txt_promedio,
                txt_nombre,
                txt_primerap,
                txt_segundoAp,
                JCB_Carrera,
                JCB_Semestre,
                txt_edad);
        Boton_Memento.setEnabled(true);
          Boton_Memento.setEnabled(false);    }//GEN-LAST:event_JM_BajasActionPerformed

    private void JM_CambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_CambiosActionPerformed
        Grafico.setEnabled(true);
        //FrameConsultas.setVisible(txt);
        ABCC.setVisible(true);
        Fondo.setBounds(0, 0, 710, 80);
        Fondo.setBackground(new java.awt.Color(161, 215, 225));
        lbl_titulo.setBounds(100, 10, 230, 70);
        lbl_titulo.setText("CAMBIOS");
        //lbl_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Cambiar_Miembro.png")));
        btn_bajas.setVisible(false);
        btn_altas.setVisible(false);
        btn_cambios.setVisible(true);
        //actualizarTablas(jTable1);
        //Estado_Cuenta.setVisible(true);
        //Caja_Estado_Cuenta.setVisible(true);
        metodoMagicoParaRestablecerComponentes(txt_numcontrol,
                txt_promedio,
                txt_nombre,
                txt_primerap,
                txt_segundoAp,
                JCB_Carrera,
                JCB_Semestre,
                txt_edad);
        Boton_Memento.setEnabled(true);
        Boton_Memento.setEnabled(false);
        
        
    }//GEN-LAST:event_JM_CambiosActionPerformed

    private void txt_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreKeyTyped
        char car= evt.getKeyChar();
            if(!(car>64&&car<91||car>96&&car<123||car==32)) {
                evt.consume();
        
            }
    }//GEN-LAST:event_txt_nombreKeyTyped

    
    private void txt_primerapKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_primerapKeyTyped
        
        char car= evt.getKeyChar();
            if(!(car>64&&car<91||car>96&&car<123||car==32)) {
                evt.consume();
        
            }
        
    }//GEN-LAST:event_txt_primerapKeyTyped

    private void txt_segundoApKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_segundoApKeyTyped
        
        char car= evt.getKeyChar();
            if(!(car>64&&car<91||car>96&&car<123||car==32)) {
                evt.consume();
        
            }
        
    }//GEN-LAST:event_txt_segundoApKeyTyped

    private void txt_edadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_edadKeyTyped
        
        char caracter=evt.getKeyChar();
            if(!(caracter>47&&caracter<58)) {
                evt.consume();
            }
             if (txt_edad.getText().trim().length() == 2) {
        evt.consume();
            }
        
    }//GEN-LAST:event_txt_edadKeyTyped

    private void JM_FuncionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_FuncionActionPerformed
        
       /* 
        String valor = JOptionPane.showInputDialog("Ingresa la ciudad").toUpperCase();
        if(valor==null || valor.trim().isEmpty()|| f1.FachadaObtenerPacienteRegion(valor)== null){
            JOptionPane.showMessageDialog(null, "Error, no hay clinicas en esa ciudad");
            
        }else{
            try {
                JOptionPane.showMessageDialog(null, f1.FachadaObtenerPacienteRegion(valor)); 
            } catch (Exception e) {
                e.printStackTrace();
            }
           
        }
      */  
    }//GEN-LAST:event_JM_FuncionActionPerformed

    private void btn_bajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bajasActionPerformed
     try {
        // Validar si no hay registros en la base de datos
        if (a1DAO.buscarAlumno("").isEmpty()) {
            JOptionPane.showMessageDialog(null, "No hay registros actualmente.");
            metodoMagicoParaRestablecerComponentes(txt_numcontrol,
                txt_promedio,
                txt_nombre,
                txt_primerap,
                txt_segundoAp,
                JCB_Carrera,
                JCB_Semestre,
                txt_edad);
            return;
        }

        // Validar si el campo del número de control está vacío
        String numeroControl = txt_numcontrol.getText().trim();
        if (numeroControl.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, ingresa un Número de Control válido.");
            metodoMagicoParaRestablecerComponentes(txt_numcontrol,
                txt_promedio,
                txt_nombre,
                txt_primerap,
                txt_segundoAp,
                JCB_Carrera,
                JCB_Semestre,
                txt_edad);
            actualizarTablas(jTable1);
            return;
        }

        // Confirmación antes de eliminar
        int confirmacion = JOptionPane.showConfirmDialog(null, 
            "¿Estás seguro de que deseas eliminar al alumno con Número de Control: " + numeroControl + "?", 
            "Confirmación", 
            JOptionPane.YES_NO_OPTION);

        if (confirmacion != JOptionPane.YES_OPTION) {
            return;
        }

        // Llama a la fachada para eliminar al alumno
        boolean eliminado = Fachada.FachadaEliminarAlumno(numeroControl);

        if (eliminado) {
            JOptionPane.showMessageDialog(null, "Alumno eliminado correctamente.");
        } else {
            JOptionPane.showMessageDialog(null, "No se encontró un alumno con el Número de Control especificado.");
        }

        // Actualizar la tabla y restablecer los componentes
        actualizarTablas(jTable1);
        metodoMagicoParaRestablecerComponentes(txt_numcontrol,
            txt_promedio,
            txt_nombre,
            txt_primerap,
            txt_segundoAp,
            JCB_Carrera,
            JCB_Semestre,
            txt_edad);

        // Habilitar el botón de restaurar (si es necesario)
        Boton_Memento.setEnabled(true);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Error: Verifica que el Número de Control sea numérico.", "Error", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Ocurrió un error inesperado: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btn_bajasActionPerformed

    private void txt_numcontrolKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_numcontrolKeyReleased
         
    }//GEN-LAST:event_txt_numcontrolKeyReleased

    private void txt_nombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreKeyReleased
        if(lbl_titulo.getText().equals("BAJAS")||lbl_titulo.getText().equals("CAMBIOS")){
                BusquedaFiltro(jTable1, "Nombre", txt_nombre.getText());
            }        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreKeyReleased

    private void jScrollPane1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseReleased
         if(lbl_titulo.getText().equals("ALTAS")){
            
        }else{
            
            txt_nombre.setText(String.valueOf( jTable1.getValueAt(jTable1.getSelectedRow(),2)));
            txt_numcontrol.setText(String.valueOf( jTable1.getValueAt(jTable1.getSelectedRow(),0)));
            txt_primerap.setText(String.valueOf( jTable1.getValueAt(jTable1.getSelectedRow(),3)));
            txt_segundoAp.setText(String.valueOf( jTable1.getValueAt(jTable1.getSelectedRow(),4)));
            JCB_Carrera.setSelectedItem(String.valueOf( jTable1.getValueAt(jTable1.getSelectedRow(),5)));
            JCB_Semestre.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(),6));
            txt_edad.setText(String.valueOf( jTable1.getValueAt(jTable1.getSelectedRow(),7)));
            txt_promedio.setText(String.valueOf( jTable1.getValueAt(jTable1.getSelectedRow(),1)));
            
            alumno estadoAnterior = new alumno(
                    Integer.parseInt(txt_numcontrol.getText()),                     
    Double.parseDouble(txt_promedio.getText()),                 
    txt_nombre.getText(),                                          
    txt_primerap.getText(),                                        
    txt_segundoAp.getText(),                                       
    JCB_Carrera.getSelectedItem().toString(),                      
    Integer.parseInt(JCB_Semestre.getSelectedItem().toString()),   
    Integer.parseInt(txt_edad.getText()));
           ultimomemento = new Memento(estadoAnterior);
             
        }
    }//GEN-LAST:event_jScrollPane1MouseReleased

    private void btn_altasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_altasActionPerformed
        try {
        if (txt_nombre.getText().isEmpty() || 
            txt_primerap.getText().isEmpty() || 
            txt_segundoAp.getText().isEmpty() || 
            txt_edad.getText().isEmpty() || 
            txt_promedio.getText().isEmpty() || 
            JCB_Carrera.getSelectedIndex() == 0 || 
            JCB_Semestre.getSelectedIndex() == 0) {

            JOptionPane.showMessageDialog(null, "VERIFICA QUE TODOS LOS CAMPOS ESTÉN COMPLETOS");
            return;
        }

        double promedio = Double.parseDouble(txt_promedio.getText());
        if (promedio < 0 || promedio > 100) {
            JOptionPane.showMessageDialog(null, "El promedio debe estar entre 0 y 100.");
            return;
        }

        if (a1DAO.buscarAlumno("").isEmpty()) {
            cont++;
            txt_numcontrol.setText(String.valueOf(cont));

            alumno nuevoAlumno = new alumno(
                cont,
                promedio,
                txt_nombre.getText(),
                txt_primerap.getText(),
                txt_segundoAp.getText(),
                JCB_Carrera.getSelectedItem().toString(),
                Integer.parseInt(JCB_Semestre.getSelectedItem().toString()),
                Integer.parseInt(txt_edad.getText())
            );

            ultimomemento = new Memento(nuevoAlumno);
            f1.FachadaAgregarAlumnos(nuevoAlumno);

            JOptionPane.showMessageDialog(null, "Alumno ingresado con éxito!");
            actualizarTablas(jTable1);
            metodoMagicoParaRestablecerComponentes(txt_numcontrol, txt_promedio, txt_nombre, txt_primerap, txt_segundoAp, JCB_Carrera, JCB_Semestre, txt_edad);
            Boton_Memento.setEnabled(true);
        } else {
            cont = a1DAO.buscarAlumno("").getLast().getNumeroControl();
            cont++;
            txt_numcontrol.setText(String.valueOf(cont));

            alumno nuevoAlumno = new alumno(
                cont,
                promedio,
                txt_nombre.getText(),
                txt_primerap.getText(),
                txt_segundoAp.getText(),
                JCB_Carrera.getSelectedItem().toString(),
                Integer.parseInt(JCB_Semestre.getSelectedItem().toString()),
                Integer.parseInt(txt_edad.getText())
            );

            ultimomemento = new Memento(nuevoAlumno);
            f1.FachadaAgregarAlumnos(nuevoAlumno);

            JOptionPane.showMessageDialog(null, "Alumno ingresado con éxito!");
            actualizarTablas(jTable1);
            metodoMagicoParaRestablecerComponentes(txt_numcontrol, txt_promedio, txt_nombre, txt_primerap, txt_segundoAp, JCB_Carrera, JCB_Semestre, txt_edad);
            Boton_Memento.setEnabled(true);
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Por favor, ingrese valores numéricos válidos en los campos correspondientes.");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Ocurrió un error inesperado: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btn_altasActionPerformed

    private void txt_numcontrolKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_numcontrolKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
        if (txt_numcontrol.getText().length() >= 8) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_numcontrolKeyTyped

    private void txt_promedioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_promedioKeyTyped
       char c = evt.getKeyChar();
    String text = txt_promedio.getText();

    // Permitir solo números, un punto decimal, y verificar longitud
    if (!Character.isDigit(c) && c != '.') {
        evt.consume();
        return;
    }

    // Evitar más de un punto decimal
    if (c == '.' && text.contains(".")) {
        evt.consume();
        return;
    }

    // Validar que los decimales no sean más de dos
    if (text.contains(".") && text.substring(text.indexOf(".") + 1).length() >= 2 && c != KeyEvent.VK_BACK_SPACE) {
        evt.consume();
        return;
    }

    // Validar rango entre 1 y 100
    try {
        String newText = c == '.' ? text + c : text + (c == KeyEvent.VK_BACK_SPACE ? "" : String.valueOf(c));
        if (!newText.isEmpty() && !newText.equals(".")) {
            double value = Double.parseDouble(newText);
            if (value < 1 || value > 100) {
                evt.consume();
            }
        }
    } catch (NumberFormatException e) {
        evt.consume();
    }


    }//GEN-LAST:event_txt_promedioKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInicio().setVisible(true);
            }
        });
    }//main
    
    public void metodoHabilitar(Component...componentes){
        for(Component x: componentes){
            if(x instanceof JTextField){
                ((JTextField)x).setEditable(true);
            } else if (x instanceof JButton) {
                ((JButton)x).setEnabled(true);
            }
        }//foreach

    }// Metodo Habilitar
    public void metodoDeshabilitar(Component...componentes){
        for(Component x: componentes){
            if(x instanceof JTextField){
                ((JTextField)x).setEditable(false);
            } else if (x instanceof JButton) {
                ((JButton)x).setEnabled(false);
            }
        }//foreach
    }// Metodo Desabilitar
    
    public void BusquedaFiltro(JTable tabla, String campo, String filtro){
      /*  try{
            
                String controlador="org.postgresql.Driver";
                String URL = "jdbc:postgresql://localhost:5432/proyecto_clinica";
                 String consulta = "SELECT * FROM paciente WHERE " + campo.toLowerCase() + "::text LIKE '" + filtro + "%' ORDER BY Idpaciente";
        
                ResultSetTableModel modeloTabla=null;
                try {
                    modeloTabla = new ResultSetTableModel(controlador,URL,consulta);
                    }  catch (ClassNotFoundException e) {
                         JOptionPane.showMessageDialog(getContentPane(), e);
                        }
                tabla.setModel(modeloTabla);
            }
              catch (SQLException e) {
            JOptionPane.showMessageDialog(getContentPane(), e);
        }*/
    }
    public void metodoMagicoParaRestablecerComponentes(JComponent ... compo){
        for (JComponent x: compo) {
            if(x instanceof JTextField){
                ((JTextField)x).setText("");
            }else if(x instanceof JComboBox){
                ((JComboBox)x).setSelectedIndex(0);
            }else if(x instanceof SpinnerModel){
                ((SpinnerModel)x).setValue(0);
            } else if (x instanceof JCheckBox) {
                ((JCheckBox)x).setSelected(false);
            }else if(x instanceof JRadioButton){
                ((JRadioButton)x).setSelected(false);
            }
        }
    }//metodoParaVaciado
    public void actualizarTablas(JTable tabla) {
    String controlador = "org.postgresql.Driver";
    String URL = "jdbc:postgresql://localhost:5432/proyecto_tutorias"; // Incluye el nombre de la base de datos
    String consulta = "SELECT * FROM public.alumno ORDER BY NumeroControl"; // Asegúrate de usar el esquema correcto

    try {
        ResultSetTableModel modeloTabla = new ResultSetTableModel(controlador, URL, consulta); // Crea el modelo una vez
        tabla.setModel(modeloTabla); // Asigna el modelo a la tabla
    } catch (ClassNotFoundException e) {
        throw new RuntimeException("Error: No se encontró el controlador de PostgreSQL", e);
    } catch (SQLException e) {
        throw new RuntimeException("Error: Problema al ejecutar la consulta SQL", e);
    }
}
//Metodo Actualizar Tablas

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame ABCC;
    private javax.swing.JPanel BG;
    private javax.swing.JButton Boton_Memento;
    private javax.swing.JPanel Fondo;
    private javax.swing.JMenuItem Grafico;
    private javax.swing.JComboBox<String> JCB_Carrera;
    private javax.swing.JComboBox<String> JCB_Semestre;
    private javax.swing.JMenuItem JM_Altas;
    private javax.swing.JMenu JM_Alumnos;
    private javax.swing.JMenuItem JM_Bajas;
    private javax.swing.JMenuItem JM_Cambios;
    private javax.swing.JMenuItem JM_Consultas;
    private javax.swing.JMenuItem JM_Funcion;
    private javax.swing.JButton btn_altas;
    private javax.swing.JButton btn_bajas;
    private javax.swing.JButton btn_cambios;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_Edad;
    private javax.swing.JLabel lbl_carrera;
    private javax.swing.JLabel lbl_img;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_numControl;
    private javax.swing.JLabel lbl_primerap;
    private javax.swing.JLabel lbl_promedio;
    private javax.swing.JLabel lbl_segundoap;
    private javax.swing.JLabel lbl_semestre;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JTextPane txt_edad;
    private javax.swing.JTextPane txt_nombre;
    private javax.swing.JTextPane txt_numcontrol;
    private javax.swing.JTextPane txt_primerap;
    private javax.swing.JTextPane txt_promedio;
    private javax.swing.JTextPane txt_segundoAp;
    // End of variables declaration//GEN-END:variables
}
